name: Validate and sort

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate
        run: python scripts/validate.py
      - name: Find Duplicated Lines
        run: python scripts/find_duplicates.py
      - name: Sort
        run: python scripts/sort_and_dedup.py
      - name: Push back to GitHub when contents changed
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Sort entries"
            git push origin main
          fi
