name: Validate

on:
  push:
    branches-ignore:
      - main  # handled separately
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate
        run: python scripts/validate.py
      - name: Find Duplicated Lines
        run: python scripts/find_duplicates.py
